### ISSUE TITLE
Unable to parse some files

### ISSUE THREAD

**Issue by ghost** [chrisballinger/python-localizable#2]
Hey! I have  been trying to parse multiple string files but I haven't been able to. After some research on your regex I was able to find that multiple comments put together individually are rejected. so i fixed them but the I tried parsing this but it failed.
`
/* Class = "UILabel"; text = "Circuit Breaker Health State"; ObjectID = "eCz-kD-Zye"; */
"eCz-kD-Zye.text" = "Circuit Breaker Health State";
`
I always end up getting this:

**Invalid syntax: /*
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sesa466157\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localizable.py", line 99, in parse_strings
    end = m.end()
AttributeError: 'NoneType' object has no attribute 'end'**

Please help.

**Comment by chrisballinger** [comment]
It's the `;` character in the comment, I'm guessing. I'm not really supporting this library but if you find a fix I'll merge it.

**Comment by svyatoslav-zubrin** [comment]
Hey. I faced the same issue today. @asmuth444 have you found any solution for it?

**Comment by ghost** [comment]
I wrote my own regex to extract key and values only. I couldn't figure out
the comments problem.

Regards,
Abhishek Roul
